services:
  - type: web
    name: portfolio
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn portfolio.wsgi:app -k uvicorn.workers.UvicornWorker"
