# Generated by Django 5.2.6 on 2025-11-26 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('goal_type', models.CharField(choices=[('BUILD_HABIT', 'Build Habit'), ('QUIT_BEHAVIOR', 'Quit Behavior')], default='BUILD_HABIT', max_length=20)),
                ('category', models.CharField(choices=[('HEALTH', 'Health'), ('PRODUCTIVITY', 'Productivity'), ('SOCIAL', 'Social'), ('PERSONAL_DEVELOPMENT', 'Personal Development'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('target_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('CUSTOM', 'Custom')], default='DAILY', max_length=10)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('SKIPPED', 'Skipped')], default='SUCCESS', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='goals.goal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'is_active'], name='goals_goal_user_id_f54208_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['start_date'], name='goals_goal_start_d_d23abc_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'created_at'], name='goals_goal_user_id_449354_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['goal', 'date'], name='goals_check_goal_id_84a0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['date'], name='goals_check_date_57f93c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('goal', 'date')},
        ),
    ]
