# Generated by Django 5.0.9 on 2024-11-27 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projects",
            old_name="url",
            new_name="cloudinary_image_url",
        ),
        migrations.AddField(
            model_name="projects",
            name="cloudinary_image_id",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projects",
            name="optimized_image_url",
            field=models.URLField(
                blank=True,
                null=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=""),
        ),
    ]
