# Generated by Django 4.2.16 on 2024-09-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='link',
            new_name='url',
        ),
    ]
