# Generated by Django 4.2.16 on 2024-09-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_link_projects_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='topics',
            field=models.CharField(default='all', help_text='Comma-separated list of topics', max_length=200),
        ),
    ]
