# Generated by Django 5.0.9 on 2024-11-27 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_projects_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
    ]
