# Generated by Django 5.0.9 on 2024-10-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_message_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
