# Generated by Django 5.0.9 on 2024-11-29 12:34

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_projects_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="projects",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
