# Generated by Django 5.0.9 on 2024-11-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_message_message_alter_projects_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="slug",
            field=models.SlugField(
                blank=True, default="djangodbmodelsfieldscharfield", max_length=100
            ),
        ),
    ]
