# Generated by Django 5.0.9 on 2024-12-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_projects_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
