# Generated by Django 5.0.9 on 2024-12-21 17:35

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_projects_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='cloudinary_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=wagtail.fields.RichTextField(),
        ),
    ]
