# Generated by Django 5.0.9 on 2024-12-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_message_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='cloudinary_image_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
