# Generated by Django 5.0.10 on 2025-01-30 18:55

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_projects_cloudinary_image_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='projects',
            name='cloudinary_image_id',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='cloudinary_image_url',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='optimized_image_url',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('cloudinary_image_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cloudinary_image_url', models.URLField(blank=True, null=True)),
                ('optimized_image_url', models.URLField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='app.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='app.projects')),
            ],
        ),
    ]
