# Generated by Django 5.0.10 on 2025-01-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_projects_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(default='Web Development', max_length=200),
        ),
        migrations.AddField(
            model_name='projects',
            name='client',
            field=models.CharField(default='Personal', max_length=200),
        ),
    ]
