# Generated by Django 5.0.10 on 2025-01-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_projects_category_projects_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile Development', 'Mobile Development'), ('Desktop Development', 'Desktop Development'), ('Machine Learning', 'Machine Learning'), ('Data Science', 'Data Science'), ('DevOps', 'DevOps'), ('Cyber Security', 'Cyber Security'), ('Networking', 'Networking'), ('Game Development', 'Game Development'), ('UI/UX Design', 'UI/UX Design'), ('Other', 'Other')], default='Web Development', max_length=100),
        ),
    ]
