# Generated by Django 5.0.10 on 2025-01-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_projects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='live',
            field=models.BooleanField(default=True),
        ),
    ]
