# Generated by Django 5.0.10 on 2025-02-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_image_live_video_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('professional', 'Professional')], default='personal', max_length=20),
        ),
    ]
