# Generated by Django 5.0.10 on 2025-02-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_projects_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='live',
            field=models.BooleanField(default=True),
        ),
    ]
