# Generated by Django 5.0.10 on 2025-02-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinks',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
