# Generated by Django 5.2 on 2025-05-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallinks',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(
                choices=[
                    ('Web Development',
                     'Web Development'),
                    ('Software Development',
                     'Software Development'),
                    ('Database Management',
                     'Database Management'),
                    ('DevOps',
                     'DevOps'),
                    ('Networking',
                     'Networking'),
                    ('UI/UX Design',
                     'UI/UX Design'),
                    ('Cyber Security',
                     'Cyber Security'),
                    ('Cloud Computing',
                     'Cloud Computing'),
                    ('Machine Learning',
                     'Machine Learning'),
                    ('Data Science',
                     'Data Science'),
                    ('Artificial Intelligence',
                     'Artificial Intelligence'),
                    ('Internet of Things',
                     'Internet of Things'),
                    ('Game Development',
                     'Game Development'),
                    ('Other',
                     'Other')],
                default='Web Development',
                max_length=100),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='SocialLinks',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
