# Generated by Django 5.2.6 on 2025-10-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_sociallinks_profile_remove_usersettings_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('period', models.CharField(help_text='e.g., 2023 - 2024', max_length=50)),
                ('institution', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('period', models.CharField(help_text='e.g., Apr. 2024 - Present', max_length=50)),
                ('company', models.CharField(max_length=200)),
                ('icon_type', models.CharField(choices=[('building', 'Building/Company'), ('laptop', 'Laptop/Remote'), ('graph-up', 'Analytics/Data'), ('code-slash', 'Development'), ('globe', 'Global/International')], default='building', max_length=20)),
                ('responsibilities', models.JSONField(default=list, help_text='List of responsibilities as JSON array')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'ordering': ['order', '-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ethan Wanyoike', max_length=100)),
                ('title', models.CharField(default='Software Engineer', max_length=100)),
                ('location', models.CharField(default='Nairobi, Kenya', max_length=100)),
                ('email', models.EmailField(default='ethanmuthoni@gmail.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('summary', models.TextField(default='A software engineer with a passion for building scalable applications and improving user experiences. Experienced in both frontend and backend development, and always eager to learn new technologies and improve my skills.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, help_text="Optional category grouping (e.g., 'Programming Languages', 'Frameworks')", max_length=100)),
                ('proficiency_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=3)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'name'],
                'managed': True,
            },
        ),
    ]
