# Generated by Django 5.2.6 on 2025-10-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_about_page_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='period',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='period',
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of education (leave blank if currently studying)', null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Check if currently studying here'),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(default='2020-01-01', help_text='Start date of education'),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of employment (leave blank if currently working)', null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Check if currently working here'),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default='2020-01-01', help_text='Start date of employment'),
        ),
    ]
