# Generated by Django 5.2.6 on 2025-10-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_add_date_ranges_to_education_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, help_text='The search query text', max_length=200, unique=True)),
                ('query_normalized', models.CharField(db_index=True, help_text='Normalized version of the query (lowercase, trimmed)', max_length=200)),
                ('count', models.PositiveIntegerField(default=1, help_text='Number of times this query has been searched')),
                ('first_searched_at', models.DateTimeField(auto_now_add=True, help_text='When this query was first searched')),
                ('last_searched_at', models.DateTimeField(auto_now=True, help_text='When this query was last searched')),
                ('result_count', models.IntegerField(default=0, help_text='Number of results returned for this query (last search)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to include this query in popular searches')),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-count', '-last_searched_at'],
                'managed': True,
                'indexes': [models.Index(fields=['-count', '-last_searched_at'], name='app_searchq_count_111aa4_idx'), models.Index(fields=['query_normalized'], name='app_searchq_query_n_94f1de_idx')],
            },
        ),
    ]
