# Generated by Django 5.0.9 on 2024-10-29 15:29

import cloudflare_images.field
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cloudflare_image_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cloudflare_image_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=cloudflare_images.field.CloudflareImagesField(blank=True, default='', null=True),
        ),
    ]
