# Generated by Django 5.0.9 on 2024-11-25 16:44

import cloudflare_images.field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_cloudflare_image_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"managed": True},
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="cloudflare_image_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="cloudflare_image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="cover_image",
            field=cloudflare_images.field.CloudflareImagesField(
                blank=True, null=True, upload_to="", variant="public"
            ),
        ),
    ]
