# Generated by Django 5.0.9 on 2024-12-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blogpostpage_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
