# Generated by Django 5.0.9 on 2024-12-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_blogpostpage_cover_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpostpage",
            name="cover_image",
        ),
    ]
