# Generated by Django 5.0.10 on 2024-12-18 18:05

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogpostpage_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for the post', null=True, upload_to=blog.models.upload_to_cloudinary),
        ),
    ]
