# Generated by Django 5.0.9 on 2024-12-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogpostpage_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='post_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='post_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
