# Generated by Django 5.0.9 on 2024-12-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpostpage_post_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostpage',
            name='cover_image',
        ),
    ]
