# Generated by Django 5.0.9 on 2024-12-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_remove_blogpostpage_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
