# Generated by Django 5.0.10 on 2025-02-16 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogpostpage_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostComment',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('content',
                 models.TextField()),
                ('created_at',
                 models.DateTimeField(
                     auto_now_add=True)),
                ('updated_at',
                 models.DateTimeField(
                     auto_now=True)),
                ('author',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='comments',
                     to=settings.AUTH_USER_MODEL)),
                ('post',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='comments',
                     to='blog.blogpostpage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
