# Generated by Django 5.2 on 2025-05-20 17:28
# flake8: noqa

from django.db import migrations


def move_cloudinary_data(apps, schema_editor):
    """
    Move cloudinary data from BlogPostPage to BlogPostImage model.
    """

    BlogPostPage = apps.get_model('blog', 'BlogPostPage')
    # get or create the BlogPostImage model
    BlogPostImage = apps.get_model('blog', 'BlogPostImage')

    for post in BlogPostPage.objects.all():
        if post.cloudinary_image_id:
            new_post_image = BlogPostImage.objects.create(
                post=post,
                cloudinary_image_id=post.cloudinary_image_id,
                cloudinary_image_url=post.cloudinary_image_url,
                optimized_image_url=post.optimized_image_url
            )
            new_post_image.save()
        else:
            new_post_image = BlogPostImage.objects.create(
                post=post,
                cloudinary_image_id=None,
                cloudinary_image_url=None,
                optimized_image_url=None
            )
            new_post_image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blogpostcomment_post_blogpostcommentreply_and_more'),
    ]

    operations = [
        migrations.RunPython(move_cloudinary_data),
    ]
