# Generated by Django 5.2.4 on 2025-07-09 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_alter_blogpostpage_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostpage",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of page views"
            ),
        ),
        migrations.CreateModel(
            name="ViewCountAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.blogpostpage",
                    ),
                ),
            ],
            options={
                "db_table": "view_count_attempts",
                "indexes": [
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="view_count__ip_addr_5ec145_idx",
                    ),
                    models.Index(
                        fields=["article", "timestamp"],
                        name="view_count__article_5e338e_idx",
                    ),
                ],
            },
        ),
    ]
