# Generated by Django 5.2.4 on 2025-07-09 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_blogpostpage_view_count_viewcountattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="viewcountattempt",
            name="view_count__article_5e338e_idx",
        ),
        migrations.AddField(
            model_name="blogpostpage",
            name="last_view_increment",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of the last view count increment",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="viewcountattempt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="view_count_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="viewcountattempt",
            name="visitor_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="viewcountattempt",
            unique_together={("article", "visitor_hash")},
        ),
        migrations.AddIndex(
            model_name="viewcountattempt",
            index=models.Index(
                fields=["article", "visitor_hash"],
                name="view_count__article_d02c31_idx",
            ),
        ),
    ]
