# Generated by Django 5.2.4 on 2025-08-08 00:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_blogpostpage_legacy_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
