# Generated by Django 5.2.6 on 2025-09-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_blogpostpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostpage',
            name='legacy_content',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='stream_content',
        ),
    ]
