# Generated by Django 5.2.6 on 2025-10-15 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_blogpostpage_legacy_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blogpostpage'),
        ),
    ]
