# Generated by Django 5.2 on 2025-05-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_transfer_auth_data'),
    ]

    operations = [
    ]
